
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package compiler_ww424;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMBER = 11;
  public static final int SEMI = 2;
  public static final int LPAREN = 7;
  public static final int MULTIPLY = 5;
  public static final int RPAREN = 8;
  public static final int ID = 10;
  public static final int error = 1;
  public static final int EQ = 9;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int MINUS = 4;
  public static final int DIVIDE = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "EQ",
  "ID",
  "NUMBER"
  };
}

