
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package compiler_ww424;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNDERSCORE = 36;
  public static final int RANGLE = 23;
  public static final int LENGTH = 31;
  public static final int SEMI = 10;
  public static final int error = 1;
  public static final int INT = 34;
  public static final int MINUS = 17;
  public static final int LANGLE = 22;
  public static final int RETURN = 30;
  public static final int ELSE = 29;
  public static final int CHARACTER = 38;
  public static final int ID = 37;
  public static final int EOF = 0;
  public static final int IF = 27;
  public static final int INTEGER = 40;
  public static final int COMMA = 8;
  public static final int MOD = 21;
  public static final int OR = 25;
  public static final int TIMES = 19;
  public static final int USE = 26;
  public static final int LPAREN = 4;
  public static final int LBRACKET = 6;
  public static final int NEGATION = 18;
  public static final int TRUE = 32;
  public static final int RBRACKET = 7;
  public static final int COLON = 9;
  public static final int RPAREN = 5;
  public static final int EQ = 11;
  public static final int DIV = 20;
  public static final int GEQ = 14;
  public static final int RBRACE = 3;
  public static final int BOOL = 35;
  public static final int AND = 24;
  public static final int EQEQ = 12;
  public static final int LEQ = 13;
  public static final int STRING = 39;
  public static final int WHILE = 28;
  public static final int FALSE = 33;
  public static final int NEQ = 15;
  public static final int LBRACE = 2;
  public static final int PLUS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "COMMA",
  "COLON",
  "SEMI",
  "EQ",
  "EQEQ",
  "LEQ",
  "GEQ",
  "NEQ",
  "PLUS",
  "MINUS",
  "NEGATION",
  "TIMES",
  "DIV",
  "MOD",
  "LANGLE",
  "RANGLE",
  "AND",
  "OR",
  "USE",
  "IF",
  "WHILE",
  "ELSE",
  "RETURN",
  "LENGTH",
  "TRUE",
  "FALSE",
  "INT",
  "BOOL",
  "UNDERSCORE",
  "ID",
  "CHARACTER",
  "STRING",
  "INTEGER"
  };
}

